CREATE TABLE "BUILDS" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "PCID" BIGINT REFERENCES COMPUTERS (ID)
);

CREATE TABLE "COMPUTERS" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "SLOTS" SMALLINT,
    "COOLING" SMALLINT,
    "PRICE" SMALLINT
);

CREATE TABLE "COMPONENTS" (
    "ID" BIGINT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    "BUILDID" BIGINT REFERENCES BUILDS (ID),
    "NAME" VARCHAR(255),
    "HEAT" SMALLINT,
    "PRICE" SMALLINT,
    "ENERGY" SMALLINT
);